### ISSUE TITLE
OverQuotaError: The API call datastore_v3.Get() required more quota than is available.

### ISSUE THREAD

**Issue by fjorgemota** [matrufsc2/matrufsc2#7]
View details in Rollbar: [https://rollbar.com/fjorgemota/MatrUFSC2/items/87/](https://rollbar.com/fjorgemota/MatrUFSC2/items/87/)

```
Traceback (most recent call last):
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/gaenv_lib/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/gaenv_lib/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/gaenv_lib/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/gaenv_lib/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/gaenv_lib/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/matrufsc2.py", line 290, in update
    return fut.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 325, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 368, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/app/robot/robot.py", line 621, in run
    response = yield self.run_worker(params)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 371, in _help_tasklet_along
    value = gen.send(val)
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/app/robot/robot.py", line 418, in run_worker
    self.check_cache_existence(campus, semester)
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/app/robot/cache_helper.py", line 104, in check_cache_existence
    }, index=True, overwrite=True)
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/app/decorators.py", line 144, in dec
    items = json.loads(json.dumps(items, cls=JSONEncoder, separators=(',', ':')))
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/__init__.py", line 250, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/base/data/home/runtimes/python27/python27_dist/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/app/json_serializer.py", line 19, in default_encoder
    return obj.to_json()
  File "/base/data/home/apps/s~matrufsc2/robot:1.382570336306801549/app/models.py", line 70, in to_json
    "teachers": ndb.get_multi(self.teachers)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/model.py", line 3849, in get_multi
    for future in get_multi_async(keys, **ctx_options)]
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 325, in get_result
    self.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 368, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 744, in get
    entity = yield self._get_batcher.add_once(key, options)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 368, in _help_tasklet_along
    value = gen.throw(exc.__class__, exc, tb)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/context.py", line 329, in _get_tasklet
    entities = yield self._conn.async_get(options, datastore_keys)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/ext/ndb/tasklets.py", line 454, in _on_rpc_completion
    result = rpc.get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 899, in get_result
    results = self.__rpcs[0].get_result()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 613, in get_result
    return self.__get_result_hook(self)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1609, in __get_hook
    self.check_rpc_success(rpc)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/datastore/datastore_rpc.py", line 1340, in check_rpc_success
    rpc.check_success()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_stub_map.py", line 579, in check_success
    self.__rpc.CheckSuccess()
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/api/apiproxy_rpc.py", line 134, in CheckSuccess
    raise self.exception
OverQuotaError: The API call datastore_v3.Get() required more quota than is available.
```

**Comment by paladini** [comment]
É treta.

**Comment by fjorgemota** [comment]
Nem é. Eu só tô testando umas otimizações malucas no robô e acabei estourando a cota do AppEngine automagicamente. hahahahah
